export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const AVATAR_LOADED = "AVATAR_LOADED";

export const PRIVATE_BOARDS_FETCHING = "PRIVATE_BOARDS_FETCHING";
export const PRIVATE_BOARDS_FETCHED = "PRIVATE_BOARDS_FETCHED";
export const PRIVATE_BOARDS_ERROR = "PRIVATE_BOARDS_ERROR";
export const SINGLE_PRIVATE_FETCHING = "SINGLE_PRIVATE_FETCHING";
export const SINGLE_PRIVATE_FETCHED = "SINGLE_PRIVATE_FETCHED";
export const SINGLE_PRIVATE_ERROR = "SINGLE_PRIVATE_ERROR";

export const TASK_UPDATE = "TASK_UPDATE";
export const TASK_ADDED = "TASK_ADDED";
export const TASK_DELETE = "TASK_DELETE";

export const CARD_ADDED = "CARD_ADDED";
export const CARD_DELETE = "CARD_DELETE";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_PACKAGE = "FETCH_ALL_PACKAGE";
export const DELETE_PACKAGE = "DELETE_PACKAGE";

export const FETCH_ALL_TEAMS = "FETCH_ALL_TEAMS";
