name: Deployment

on:
  push:
    branches: [frontend]
  pull_request:
    branches: [frontend]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          ref: frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps and run tests
        run: |
          npm install --silent
          npm run test:action
      - name: Build app
        run: |
          npm run build
      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: public
