name: Deployment

on:
  push:
    branches: [placeholder_front]
  pull_request:
    branches: [placeholder_front]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          ref: placeholder_front

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps and run tests
        run: |
          npm install --silent
      - name: Build app
        run: |
          npm run build
      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: build
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
               cd /vm_docker/trello_copy
               rm -r react_www
               git clone -b build https://github.com/PHReactive/trello_copy.git react_www
               
