name: Waiting for checks and deploy

on:
  push:

jobs:
 deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER_LARAVEL }}
            password: ${{ secrets.PASSWORD_LARAVEL }}
            port: ${{ secrets.PORT_LARAVEL }}
            timeout: 120s
            script: |
               cd /var
               rm -r www
               git clone -b laravel https://github.com/PHReactive/trello_copy.git www
               cd www 
               composer install
               cp .env.example .env
               php artisan key:generate
               chmod -R 777 storage
               php artisan migrate:reset
               php artisan migrate:refresh --seed
               php artisan passport:install

      - name: Step to deploy
        run: echo 'success!'
